version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Kuala_Lumpur
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Kuala_Lumpur
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Kuala_Lumpur
    open-pull-requests-limit: 3
